-- DROP DATABASE
DROP DATABASE IF EXISTS z4ygrf9joqq933vg;

-- CREATE DATABASE
CREATE DATABASE z4ygrf9joqq933vg;

USE z4ygrf9joqq933vg;

CREATE TABLE todos (
id INT AUTO_INCREMENT NOT NULL,
description VARCHAR(255),
createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id)
);